added eventsdata
GDSC-IIIT-V/gdsc-iiitv-website pull request #8
Opened 2022-10-24 16:54 UTC by ShravaniAK

added recent events data of gdsc iiitv.

2022-10-24 16:54 UTC, ShravaniAK commented
resolve #7

2022-10-27 14:39 UTC, Im-Madhur-Gupta commented on src/Components/Events/util/EventsData.js
> +    title: "Building Apps with Flultter",
Correct the typo.

2022-10-27 14:54 UTC, Im-Madhur-Gupta requested changes
Please remove the top 4 events from the EventsData array in EvetsData.js.

2022-10-28 11:24 UTC, ShravaniAK commented on src/Components/Events/util/EventsData.js
> +    title: "Building Apps with Flultter",
sir i am not getting , which typo needs to be corrected?

2022-10-29 13:50 UTC, Im-Madhur-Gupta commented on src/Components/Events/util/EventsData.js
> +    title: "Building Apps with Flultter",
Check the spelling of Flutter.

2022-10-29 13:50 UTC, Im-Madhur-Gupta requested changes
Fix the typo, everything else looks good.

2022-10-31 13:09 UTC, Im-Madhur-Gupta approved these changes
LGTM

2022-10-31 13:09 UTC, merged