Updated Leads and Volunteers of 2022-23 and included their Profile Pictures
GDSC-IIIT-V/gdsc-iiitv-website pull request #9
Opened 2022-10-26 13:06 UTC by Ayush-Khandelwal28

#4

2022-10-27 15:11 UTC, Im-Madhur-Gupta requested changes
You have removed the imgurl property, you need to add it to all the objects in the array. The value would be a relative link to that person's image file.

2022-10-30 18:09 UTC, Ayush-Khandelwal28 commented
Added imgurl property

2022-11-20 17:17 UTC, Im-Madhur-Gupta approved these changes

2022-11-20 17:17 UTC, Im-Madhur-Gupta commented
LGTM

2022-11-20 17:17 UTC, merged